# This file was generated by GoReleaser. DO NOT EDIT.
cask "runny" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f58dd13f257328d7b320d204b959bdace08ee05bcf3ccb7a833259aa8e6816ce"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f696e4e748b45f2cb098e04ad3a2c5c175e9126a334b1b63995bd854c977a095"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0eaaf6a283a7f676b020846e72d0a4762ce54450dbf982c48295742edd4b4566"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c055e2300a3581f4bae44401773df0cee68d79e476f4a389b42962bd6b1b2fa"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_linux_arm64.tar.gz"
    end
  end

  name "runny"
  desc "Run shell commands across selected child directories from a TUI"
  homepage "https://github.com/theopoc/runny"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runny"

  # No zap stanza required

  caveats <<~EOS
    To trust the tap before install:
      brew tap theopoc/tap
      brew trust --tap theopoc/tap
  EOS
end
