# This file was generated by GoReleaser. DO NOT EDIT.
cask "runny" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "07f5d9b00477ae64086e23c81ce8e5e4b95147ce2cd3f49709f52b31d1444306"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "24f5cab9415d3c90aba7347e7b5f4603ce1f10689f32dbfbef3b080d8825b202"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d56b91d8cd85fcbbcc08575377938ed6efe4261b699fd0337582cc9b33fa2740"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "adc556940af03bfc2be4f91c1f57b00fbd1e087bac736d0fab750bc7ef25cbcd"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_linux_amd64.tar.gz"
    end
  end

  name "runny"
  desc "Run shell commands across selected child directories from a TUI"
  homepage "https://github.com/theopoc/runny"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runny"

  # No zap stanza required

  caveats <<~EOS
    To trust the tap before install:
      brew tap theopoc/tap
      brew trust --tap theopoc/tap
  EOS
end
