# This file was generated by GoReleaser. DO NOT EDIT.
cask "runny" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7eb977987a70782cec14b3e8198faf293cb4e9026e508d8193410be699545f19"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fb8e3cd430d693ca2a14d30732c4ee898dfc73fea316e02df09f4bcad172f8d"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a820c8c9c77edf9872a9c8eb8246cc1278c2a433e7cab99988c34eee9471ceb"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca08423ebb20764cf3317af4bbb0309b104dd31b999e14867e535494af49a647"
      url "https://github.com/theopoc/runny/releases/download/v#{version}/runny_#{version}_linux_arm64.tar.gz"
    end
  end

  name "runny"
  desc "Run shell commands across selected child directories from a TUI"
  homepage "https://github.com/theopoc/runny"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runny"

  # No zap stanza required

  caveats <<~EOS
    To trust the tap before install:
      brew tap theopoc/tap
      brew trust --tap theopoc/tap
  EOS
end
